rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'
LOGIN_URL = 'rango:login'

urlpatterns = [
	path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('category/<slug:category_name_slug>/upload/', views.add_meme, name='upload'),
    path('like_meme/', views.LikeMemeView.as_view(), name='like_meme'),
    path('dislike_meme/', views.DislikeMemeView.as_view(), name='dislike_meme'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),

]

rate_my_meme_coursework/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('', views.index, name='index'),
	path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

 
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='profile_images', blank=True)
   
    def __str__(self):
        return self.user.username
   
   
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(unique=True)
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
    
    class Meta:
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name


class Meme(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    image = models.ImageField(upload_to='media')
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Meme, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.title

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import UserProfile, Meme

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password',)

class UserProfileForm(forms.ModelForm):

	class Meta:
		model = UserProfile
		fields = ('picture', )


class MemeForm(forms.ModelForm):
	title = forms.CharField(max_length=128,
							help_text="Please enter the title of the meme.")
	image = forms.ImageField()

	class Meta:
		model = Meme
		exclude = ('category', 'likes', 'dislikes', 'slug' )

rango/views.py
from rango.forms import UserForm, UserProfileForm, MemeForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect, render
from rango.models import Category, Meme, UserProfile
from datetime import datetime
from django.core.paginator import Paginator
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User

def index(request):
    meme_list = Meme.objects.order_by('-likes')

    paginator = Paginator(meme_list,1)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)


    visitor_cookie_handler(request)

    response =  render(request, 'rango/index.html', {'page_obj': page_obj})
    return response


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        meme_list = Meme.objects.filter(category=category)
        paginator = Paginator(meme_list,1)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context_dict['page_obj'] = page_obj
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['page_obj'] = None

    return render(request, 'rango/category.html', context=context_dict)

def add_meme(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    if category is None:
        return redirect('/rango/')

    form = MemeForm()

    if request.method == 'POST':
        form = MemeForm(request.POST, request.FILES)
        if form.is_valid():
            if category:
                meme = form.save(commit=False)
                meme.category = category
                meme.likes = 0
                meme.dislikes = 0
                meme.save()

                return redirect(reverse('rango:show_category',
                                        kwargs={'category_name_slug':
                                        category_name_slug}))
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/upload.html', context=context_dict)


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'rango/register.html',
                  context = {'user_form': user_form,
                             'profile_form': profile_form,
                             'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))

            else:
                return HttpResponse("Your account is disabled.")

        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, 'rango/login.html')

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)

    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(request.COOKIES.get('visits', '1'))
    last_visit_cookie = request.COOKIES.get('last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits

class LikeMemeView(View):
    @method_decorator(login_required)
    def get(self, request):
        meme_id = request.GET['meme_id']

        try:
            meme = Meme.objects.get(id=int(meme_id))
        except Meme.DoesNotExist:
            return HttpResponse(-1)
        except ValueError:
            return HttpResponse(-1)

        meme.likes = meme.likes + 1
        meme.save()

        return HttpResponse(meme.likes)

class DislikeMemeView(View):
    @method_decorator(login_required)
    def get(self, request):
        meme_id = request.GET['meme_id']

        try:
            meme = Meme.objects.get(id=int(meme_id))
        except Meme.DoesNotExist:
            return HttpResponse(-1)
        except ValueError:
            return HttpResponse(-1)

        meme.dislikes = meme.dislikes + 1
        meme.save()

        return HttpResponse(meme.dislikes)

class ProfileView(View):
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None

        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'picture': user_profile.picture})
        return (user, user_profile, form)

    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}
        return render(request, 'rango/profile.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))

        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('rango:profile', user.username)
        else:
            print(form.errors)

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}
        return render(request, 'rango/profile.html', context_dict)

templates/rango/account.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}

{% block title_block %}
	Account
{% endblock %}

templates/rango/base-old.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}

<html>
	<head>
		<title>
			Rango -
			{% block title_block %}
				Rate My Meme
			{% endblock %}
		</title>
	</head>
	<body>
		<div>
		{% block body_block %}
		{% endblock %}
		</div>
		
		<hr />
		<div>
			<ul>
				{% if user.is_authenticated %}
					<li><a href="{% url 'rango:logout' %}">Logout</a></li>
				{% else %}
					<li><a href="{% url 'rango:register' %}">Sign Up</a></li>
					<li><a href="{% url 'rango:login' %}">Login</a></li>
				{% endif %}
					<li><a href="{% url 'rango:index' %}">Index</a></li>
					<li><a href="{% url 'rango:allmemes' %}">All Memes</a></li>
			</ul>

		</div>
		<script src="{% static "js/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
		<script src="{% static "js/rango-jquery.js" %}" crossorigin="anonymous"></script>
	</body>
</html>

templates/rango/base.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>
        Rango - 
		{% block title_block %} 
		Rate My Meme! 
		{% endblock %}
    </title>
    
    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    </head>
    
    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rate My Meme</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}">Logout</a></li>
						
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:register' %}">Register Here</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>
        
        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
                    </div>
                </nav>
                
                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">		
                    {% block body_block %}{% endblock %}
                    
                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a class="btn btn-primary" href="#">Back to top</a></p>
                    </footer>
                </main>
            </div>
        </div>
        
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static "js/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
        <script src="{% static "js/rango-jquery.js" %}" crossorigin="anonymous"></script>
        <script src="{% static "js/rango-ajax.js" %}" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    </body>
</html>

templates/rango/categories.html
<ul class="nav flex-column">
	{% if categories %}
		{% for c in categories %}
			{% if c == current_category %}
				<li class="nav-item">
				<a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
					<span data-feather="archive"></span>{{ c.name }}
				</a>
				</li>
			{% else %}
				<li class="nav-item">
				<a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
					<span data-feather="archive"></span>{{ c.name }}
				</a>
				</li>
			{% endif %}
		{% endfor %}
	{% else %}
		<li class="nav-item">There are no categories present.</li>
	{% endif %}
</ul>

templates/rango/category.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
	Category
{% endblock %}

{% block body_block %}
	<head>
		<title>Rango</title>
	</head>

	<body>
		<div>
			{% if category %}
				<div class="jumbotron p-4">
					<div class="container">
						<h1 class="jumbotron-heading">{{category.name}}</h1>
						<div class="float-right">
							{% if user.is_authenticated %}
								<a class="btn btn-primary" href="{% url 'rango:upload' category.slug %}">Add Meme to this category</a> <br />
							{% endif %}
						</div>
					</div>
				</div>
				{% if page_obj %}
					<div>
            			{% for meme in page_obj %}
            				<h3>{{ meme.title }}</h3>
            				<div  class="jumbotron p-3">
            					<img src="{{MEDIA_URL}}{{meme.image}}" class="slider-img" max-width="500" height="400"/>
            				</div>
            				<div class ="p-3">
            					<strong id="like_count">{{ meme.likes }}</strong> likes
            					{% if user.is_authenticated %}
            					<button id="like_btn"
            							data-memeid="{{ meme.id }}"
            							class="btn btn-primary btn-sm"
            							type="button">
            						<span data-feather="thumbs-up"></span>
            						Like Meme
            					</button>
            					{% endif %}
            				</div>

            				<div class="p-3">
            					<strong id="like_count">{{ meme.dislikes }}</strong> dislikes
            					{% if user.is_authenticated %}
            					<button id="dislike_btn"
            							data-memeid="{{ meme.id }}"
            							class="btn btn-primary btn-sm"
            							type="button"
            							button class=red>
            						<span data-feather="thumbs-down"></span>
            						Dislike Meme
            					</button>
            					{% endif %}
            				</div>

            			{% endfor %}
            			<br />
            			<div class ="pagination">
            				<span class="step-links">
            			        {% if page_obj.has_previous %}
            			            <a class="btn btn-primary btn-sm" href="?page=1">&laquo; First</a>
            			            <a class="btn btn-primary btn-sm" href="?page={{ page_obj.previous_page_number }}">previous</a>
            			        {% endif %}

            			        <span class="current">
            			            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            			        </span>

            			        {% if page_obj.has_next %}
            			            <a class="btn btn-primary btn-sm" href="?page={{ page_obj.next_page_number }}">next</a>
            			            <a class="btn btn-primary btn-sm" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
            			        {% endif %}
            		    	</span>
            			</div>
            		</div>
				{% else %}
					<strong>No memes currently in category.</strong>
				{% endif %}
					</div>
			{% else %}
				The specified category does not exist.
			{% endif %}
		</div>
	</body>
{% endblock %}

templates/rango/index.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load static %}


{% block title_block %}
	Homepage
{% endblock %}

{% block body_block %}
	<div class="jumbotron p-3">
		<div class="container">
			<div>
				<h1 class="jumbotron-heading">
				{% if user.is_authenticated %}
					Hi {{ user.username }}!
				{% else %}
					hey there partner!
				{% endif %}
				</h1>
				<strong>{{ boldmessage }}</strong>
			</div>
		</div>
	</div>
	<div>
	<body>
		<div>
			{% for meme in page_obj %}
				<h3>{{ meme.title }}</h3>
				<div  class="jumbotron p-3">
					<img src="{{MEDIA_URL}}{{meme.image}}" class="slider-img" max-width="500" height="400"/>
				</div>
				<div class ="p-3">
					<strong id="like_count">{{ meme.likes }}</strong> likes
					{% if user.is_authenticated %}
					<button id="like_btn"
							data-memeid="{{ meme.id }}"
							class="btn btn-primary btn-sm"
							type="button">
						<span data-feather="thumbs-up"></span>
						Like Meme
					</button>
					{% endif %}
				</div>

				<div class="p-3">
					<strong id="like_count">{{ meme.dislikes }}</strong> dislikes
					{% if user.is_authenticated %}
					<button id="dislike_btn"
							data-memeid="{{ meme.id }}"
							class="btn btn-primary btn-sm"
							type="button"
							button class=red>
						<span data-feather="thumbs-down"></span>
						Dislike Meme
					</button>
					{% endif %}
				</div>

			{% endfor %}
			<br />
			<div class ="pagination">
				<span class="step-links">
			        {% if page_obj.has_previous %}
			            <a class="btn btn-primary btn-sm" href="?page=1">&laquo; Most Liked</a>
			            <a class="btn btn-primary btn-sm" href="?page={{ page_obj.previous_page_number }}">previous</a>
			        {% endif %}

			        <span class="current">
			            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
			        </span>

			        {% if page_obj.has_next %}
			            <a class="btn btn-primary btn-sm" href="?page={{ page_obj.next_page_number }}">next</a>
			            <a class="btn btn-primary btn-sm" href="?page={{ page_obj.paginator.num_pages }}">Least Liked &raquo;</a>
			        {% endif %}
		    	</span>
			</div>
		</div>
	</body>
	</div>
{% endblock %}

templates/rango/profile.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
	Profile for {{ selected_user.username }}
{% endblock %}

{% block body_block %}
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">{{ selected_user.username }}'s Profile</h1>
		</div>
	</div>

	<div class="container">
		<div class="row">
		<div class="jumbotron p-3">
			<img src="{{ MEDIA_URL }}{{ user_profile.picture }}"
				 width="300"
				 height="300"
				 alt="{{ selected_user.username }}'s profile image" />
			<br />
		</div>
			<div class="p-5">
				{% if selected_user == user %}
				<form method="post" action="." enctype="multipart/form-data">
					{% csrf_token %}
					{{ form.as_p }}

					<input type="submit" value="Update Profile" />
				</form>
				{% else %}
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load static %}
<style>
form {text-align: center;}
</style>
{% block title_block %}
	Register
{% endblock %}

{% block body_block %}
	<div class="jumbotron p-5">
		<h1 class="jumbotron-heading">Register</h1>
	</div>
	{% if registered %}
		<strong>Thank you for registering!</strong>
		<a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
	{% else %}
			<form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">

				{% csrf_token %}

				{{ user_form.as_p }}
				{{ profile_form.as_p }}

				<input type="submit" name="submit" value="Register" />
			</form>
	{% endif %}
{% endblock %}

templates/rango/upload.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
	Add a Meme
{% endblock %}

{% block body_block %}
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">Add a Page to {{category.name}}</h1>
		</div>
	</div>
	<div class="container">
		<form class="form-control-file" method="post" enctype="multipart/form-data">
        	{% csrf_token %}
        	{{ form.as_p }}
        	<button type="submit" class="btn btn-primary">Submit</button>
    	</form>
	</div>
{% endblock %}